import { Inter } from 'next/font/google'
import '../globals.css'



const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'The Meal App',
  description: 'Generated by create next app',
}

export default function HomeLayou({ children }) {
  return (
    <html lang="en">
      
      <body className="bg-yellow text-black" >{children}</body>
    </html>
  )
}